name: trivol
channels:
  - pyg
  - anaconda
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=8.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libopenblas=0.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openblas-devel=0.3.2
  - openh264=2.1.1
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - readline=8.2
  - requests=2.28.1
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - typing_extensions=4.3.0
  - urllib3=1.26.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.3.0
    - addict==2.4.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - anyio==3.7.0
    - arrow==1.2.3
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - blessed==1.20.0
    - brotli==1.0.9
    - cachetools==5.2.0
    - click==8.1.3
    - configargparse==1.5.3
    - contourpy==1.0.5
    - croniter==1.3.15
    - cycler==0.11.0
    - dash==2.6.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - dateutils==0.6.12
    - debugpy==1.6.3
    - decorator==5.1.1
    - deepdiff==6.3.0
    - einops==0.5.0
    - entrypoints==0.4
    - exceptiongroup==1.1.1
    - executing==1.1.1
    - fastapi==0.98.0
    - fastjsonschema==2.16.2
    - flask==2.2.2
    - flask-compress==1.13
    - fonttools==4.38.0
    - frozenlist==1.3.1
    - fsspec==2022.10.0
    - future==0.18.2
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - h11==0.14.0
    - imageio==2.31.1
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - inquirer==3.1.3
    - ipykernel==6.16.2
    - ipython==8.5.0
    - ipywidgets==8.0.2
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.16.0
    - jupyter-client==7.4.4
    - jupyter-core==4.11.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - kornia==0.6.8
    - lazy-loader==0.2
    - lightning==2.0.4
    - lightning-cloud==0.5.37
    - lightning-utilities==0.8.0
    - lpips==0.1.4
    - markdown==3.4.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - minkowskiengine==0.5.4
    - multidict==6.0.2
    - nbformat==5.5.0
    - nest-asyncio==1.5.6
    - networkx==3.1
    - oauthlib==3.2.2
    - open3d==0.16.0
    - opencv-python==4.6.0.66
    - ordered-set==4.1.0
    - packaging==21.3
    - pandas==1.5.1
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - plotly==5.11.0
    - prompt-toolkit==3.0.31
    - protobuf==3.19.6
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.9
    - pydeprecate==0.3.1
    - pygments==2.13.0
    - pyjwt==2.7.0
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - python-multipart==0.0.6
    - pytorch-fid==0.2.1
    - pytorch-lightning==2.0.4
    - pytz==2022.5
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - readchar==4.0.5
    - requests-oauthlib==1.3.1
    - rich==13.4.2
    - rsa==4.9
    - scikit-image==0.21.0
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - stack-data==0.5.1
    - starlette==0.27.0
    - starsessions==1.3.0
    - tenacity==8.1.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - torchmetrics==0.10.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - uvicorn==0.22.0
    - wcwidth==0.2.5
    - websocket-client==1.6.1
    - websockets==11.0.3
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - yarl==1.8.1
    - zipp==3.10.0
